# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QtWidgetsApplication1
DESTDIR = ./x64/Debug
QT += printsupport
CONFIG += debug
LIBS += -L"../../../QT/5.13.0/msvc2017_64/lib"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(QtWidgetsApplication1.pri)
